name: Crypto Homie
favicon: null
layout_spectrum: 0.17428
typography_spectrum: 0.88957
title: '<a href="https://bleutrade.com/home/21901" target="_blank" title="Bleutrade Cryptocurrency Exchange"><img src="https://bleutrade.com/imgs/banners/BleutradeAds1-728x90.gif" alt="Bleutrade Cryptocurrency Exchange" title="Bleutrade Cryptocurrency Exchange"/></a>'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.87638103752397
  lightness: 0.25
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
