name: Crypto Homie
favicon: null
layout_spectrum: 0.2921036093030125
typography_spectrum: 0.594266468193382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.87638103752397
  lightness: 0.13483766675926745
  saturation: 0.9319166319910437
  rhythmicContrast: 0.9255561949685216
purpose: []
